spring.datasource.url=jdbc:postgresql://localhost:5432/course_db
spring.datasource.username=werther
spring.datasource.password=SenhaForte0828

# Remova ou comente a linha do dialect se quiser, o Spring 3 detecta sozinho
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true